# Generated by Django 2.1.5 on 2019-03-19 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Event'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='posting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Posting'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Profile'),
        ),
    ]
