# Generated by Django 2.1.5 on 2019-03-19 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_merge_20190319_1625'),
        ('main_app', '0011_auto_20190319_1702'),
    ]

    operations = [
    ]
