# Generated by Django 2.1.5 on 2019-03-19 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_merge_20190319_1802'),
        ('main_app', '0012_merge_20190319_1801'),
    ]

    operations = [
    ]
