# Generated by Django 2.1.5 on 2019-03-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.CharField(default='https://i.imgur.com/1WGonoD.png', max_length=200),
        ),
    ]
