# Generated by Django 2.1.5 on 2019-03-15 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_photo'),
        ('main_app', '0004_profile_profile_pic'),
    ]

    operations = [
    ]
