# Generated by Django 2.1.5 on 2019-03-16 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_merge_20190315_2102'),
        ('main_app', '0005_merge_20190315_2032'),
    ]

    operations = [
    ]
