# Generated by Django 2.1.5 on 2019-03-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_merge_20190316_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='zip_code',
            field=models.IntegerField(default=0),
        ),
    ]
