# Generated by Django 2.1.5 on 2019-03-18 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_profile_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Event'),
        ),
        migrations.AddField(
            model_name='photo',
            name='posting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Posting'),
        ),
        migrations.AddField(
            model_name='photo',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Profile'),
        ),
    ]
