# Generated by Django 2.1.5 on 2019-03-19 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alert_author'),
        ('main_app', '0008_auto_20190318_2254'),
    ]

    operations = [
    ]
