# Generated by Django 2.1.5 on 2019-03-19 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_profile_profile_pic'),
        ('main_app', '0009_merge_20190319_1548'),
    ]

    operations = [
    ]
